name: "Holochain release dispatch"

on:
  push:
    tags:
      # Expect tags to be `holochain-<semver-version>`
      - holochain-*

jobs:
  holochain-tag-created:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["holochain/holonix"]
    steps:
      - name: dispatch
        env:
          GH_TOKEN: ${{ secrets.HRA_GITHUB_TOKEN }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ matrix.target }}/dispatches \
            -f "event_type=holochain-released" -F "client_payload[tag]=${{ github.ref_name }}"
